using System.Text;
using Module_05_Cloud_Deployment.Models;

namespace Module_05_Cloud_Deployment.Services;

public sealed class ResourceManifestService
{
    public List<ResourceManifest> BuildManifests(CloudBlueprint blueprint, DeploymentPlanRequest request)
    {
        var manifests = new List<ResourceManifest>();
        foreach (var component in blueprint.Components)
        {
            var manifest = new ResourceManifest
            {
                ComponentName = component.Name,
                Type = component.Type,
                Parameters = new Dictionary<string, string>(component.Configuration, StringComparer.OrdinalIgnoreCase)
            };

            if (!manifest.Parameters.ContainsKey("image") && !string.IsNullOrWhiteSpace(component.Image))
            {
                manifest.Parameters["image"] = component.Image;
            }

            foreach (var @override in request.Overrides)
            {
                manifest.Parameters[@override.Key] = @override.Value;
            }

            manifest.ProvisioningScript = BuildScript(blueprint.Provider, component);
            manifest.HealthProbe = component.Configuration.TryGetValue("healthProbe", out var probe)
                ? probe
                : "/health";
            manifest.Secrets = BuildSecrets(component);
            manifests.Add(manifest);
        }

        return manifests;
    }

    private static string BuildScript(string provider, DeploymentComponent component)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Provisioning script generated by ResourceManifestService");
        switch (provider.ToLowerInvariant())
        {
            case "azure":
                builder.AppendLine($"az deployment group create --resource-group rg-ai --template-file {component.Name}.bicep");
                builder.AppendLine("az monitor autoscale create --name autoscale --resource-group rg-ai");
                break;
            case "aws":
                builder.AppendLine("aws cloudformation deploy --template-file template.yaml --stack-name ai-stack");
                builder.AppendLine("aws application-autoscaling put-scaling-policy --service-namespace ecs");
                break;
            default:
                builder.AppendLine("echo 'Provisioning steps for provider not specified'");
                break;
        }

        builder.AppendLine("# Configure observability");
        builder.AppendLine("echo 'Configuring metrics and logging'");
        return builder.ToString();
    }

    private static Dictionary<string, string> BuildSecrets(DeploymentComponent component)
    {
        var secrets = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["connectionString"] = "{{vault:connection-string}}",
            ["apiKey"] = "{{vault:api-key}}"
        };

        if (component.Configuration.TryGetValue("database", out var database))
        {
            secrets["databaseConnection"] = $"{{vault:{database}-connection}}";
        }

        return secrets;
    }
}
